### ISSUE TITLE
familiar window speech problem

### ISSUE THREAD

**Issue by ghost** [WarlockFE/warlock2#27]
In Dragonrealms, when using Distant Gaze to view a remote room, if you have DG output going to the familiar window, all data is sent there like usual except that any speech that is said in the remote room is sent to the main story window instead of the familiar window.

Debug info:

normal person speaking in my room--------

```
<pushStream id="talk"/><preset id='speech'>xxxx asks</preset>, "Hello?"
<popStream/><preset id='speech'>xxxx asks</preset>, "Hello?"
```

person speaking in remote room with familiar window open but speech still shows up in main story window--------

```
<pushStream id="familiar" ifClosedStyle="watching"/><pushStream id="talk"/><preset id='speech'>xxxx says</preset>, "Hello."
<popStream/><preset id='speech'>xxxx says</preset>, "Hello."
```

**Comment by sproctor** [comment]
Sorry for not responding right away. I just got to test this. We don't support multiple streams on the stack correctly. Mostly because I hadn't seen this before and didn't know how it was supposed to be handled. I'll fix this and keep you updated.

**Comment by sproctor** [comment]
Okay, I have this fixed in git. It'll be in my snapshot once the server is back in order and it will be in the regular snapshot when I decide to push my work over to there.
