### ISSUE TITLE
error on startup

### ISSUE THREAD

**Issue by nebula656** [WarlockFE/warlock2#28]
I downloaded updates that were available today (2/17).  Everything worked fine until I quit the app and started it up again.  Now I'm getting this dialog:

An error has occurred.
See the log file
/Applications/warlock2/warlock2.app/Contents/MacOs/workspace/.metadata/.log.

Also, the main game window shows a red ! with: Could not create the view: INSTANCE

All my smaller windows show a red ! with: Could not create the view: Could not initialize class cc.warlock.rcp.configuration.GameViewConfiguration

I'm running Mac OS 10.8.2

**Comment by sproctor** [comment]
Alas, I don't have a Mac to test with. Could you try the build at http://build.warlock.cc/sproctor/2.0.0.110_snapshot/ and see if you have any better luck there? If not, could you attach that log file it references?

**Comment by nebula656** [comment]
Okay, I tried the build you linked to.  It downloaded to it's own folder so I opened it as a separate instance on my desktop.  I was able to start it up and log on.  I copied the contents of the old configuration folder to the new folder and was able to preserve my settings (sort of; a few things got switched around with the highlights somehow--it seems a bunch of the colors got moved down one string.)

The main problem I'm having now is that the Field Experience and Room Windows are not working.  Nothing is showing up there.  I'm getting ">" prompts in the game window every few seconds that weren't there before.  All other windows appear to be working fine.  Not sure if I'm doing something wrong with copying folders and such (I have no idea what I'm doing).

Really digging the new timers, though!  Any suggestions at this point before I muck it up even further?

As far as the old instance goes, I found the log file.  I'm going to email it to you directly.

**Comment by sproctor** [comment]
The important file is named cc.warlock.prefs. The next version is going to have the config files put ~/.warlock2. I wouldn't copy anything else. I don't know that it's causing issues, but it might. The colors being wrong could be a bug. If you can repeat it, please open a bug for it.

**Comment by sproctor** [comment]
I'm going to close this since it seems like it's okay now.
