### ISSUE TITLE
Column fonts not rendering

### ISSUE THREAD

**Issue by nebula656** [WarlockFE/warlock2#32]
I normally have two different fonts for columns and for the main text.  As of two updates ago, everything started appearing as the main text font (experience, info, health, etc is no longer my preferred fixed-width font).  Nothing seems to happen when I mess with it in preferences.  The main window font seems to be overriding the column font.

**Comment by sproctor** [comment]
I actually noticed this a few minutes ago and started investigating. I re-did some of the style code yesterday. It seems that I missed the part where it sets the font for mono-spaced fonts. I'll have it fixed momentarily.

**Comment by nebula656** [comment]
You're the man!  Thank you.

By the way, I've been PSYCHED about all these updates.  I can't tell you how awesome these timers are--they make the game experience A LOT more enjoyable, as my eyes don't have to dart all over the place.  Kudos.

No other problems so far!  Everything else is running smoothly, including my old settings.  (I tried to only copy the file you mentioned, but that didn't work.  I copied the entire configuration folder again, even though you said not to.  After a few hiccups it somehow worked -- I have no idea how.  The settings have been stable throughout all the updates you've done over the past week or so.)

I really hope Simutronics compensates you for actually making this game playable and fun on a Mac!

**Comment by sproctor** [comment]
So, moving the settings to {user.home}/.warlock2 seemed to break things on the first run. I had to move them back. I might try it again sometime. We're looking to put out an official release soon and I'm trying to kill as many bugs as I can before that happens.

I've committed the fix for this and it is building currently. It should be on the update site in a few minutes.
