### ISSUE TITLE
error on startup

### ISSUE THREAD

**Issue by nebula656** [WarlockFE/warlock2#37]
An error as occurred.

See the log file
/Applications/warlock2/configuration/1362326690084.log.

!SESSION 2013-03-03 11:04:49.844 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.6.0_41
java.vendor=Apple Inc.
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -keyring /Users/xxxxxxxx/.eclipse_keyring -showlocation
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/xxxxxxxxx/.eclipse_keyring -showlocation

!ENTRY org.eclipse.equinox.app 0 0 2013-03-03 11:04:50.446
!MESSAGE Product cc.warlock.rcp.product could not be found.

!ENTRY org.eclipse.osgi 2 0 2013-03-03 11:04:50.500
!MESSAGE One or more bundles are not resolved because the following root constraints are not resolved:
!SUBENTRY 1 org.eclipse.osgi 2 0 2013-03-03 11:04:50.500
!MESSAGE Bundle update@plugins/cc.warlock.rcp_2.0.0.2355_sproctor/ was not resolved.
!SUBENTRY 2 cc.warlock.rcp 2 0 2013-03-03 11:04:50.500
!MESSAGE Missing required bundle org.eclipse.equinox.p2.operations_0.0.0.
!SUBENTRY 2 cc.warlock.rcp 2 0 2013-03-03 11:04:50.500
!MESSAGE Missing required bundle org.eclipse.equinox.p2.updatechecker_0.0.0.
!SUBENTRY 2 cc.warlock.rcp 2 0 2013-03-03 11:04:50.500
!MESSAGE Missing required bundle org.eclipse.equinox.ds_0.0.0.
!SUBENTRY 2 cc.warlock.rcp 2 0 2013-03-03 11:04:50.500
!MESSAGE Missing required bundle org.eclipse.equinox.event_0.0.0.
!SUBENTRY 2 cc.warlock.rcp 2 0 2013-03-03 11:04:50.500
!MESSAGE Missing required bundle org.eclipse.equinox.p2.updatesite_0.0.0.

!ENTRY org.eclipse.osgi 2 0 2013-03-03 11:04:50.502
!MESSAGE The following is a complete list of bundles which are not resolved, see the prior log entry for the root cause if it exists:
!SUBENTRY 1 org.eclipse.osgi 2 0 2013-03-03 11:04:50.502
!MESSAGE Bundle cc.warlock.rcp.stormfront_2.0.0.2355_sproctor [375] was not resolved.
!SUBENTRY 2 cc.warlock.rcp.stormfront 2 0 2013-03-03 11:04:50.502
!MESSAGE Missing required bundle cc.warlock.rcp_0.0.0.
!SUBENTRY 1 org.eclipse.osgi 2 0 2013-03-03 11:04:50.502
!MESSAGE Bundle cc.warlock.rcp_2.0.0.2355_sproctor [376] was not resolved.
!SUBENTRY 2 cc.warlock.rcp 2 0 2013-03-03 11:04:50.502
!MESSAGE Missing required bundle org.eclipse.equinox.p2.operations_0.0.0.
!SUBENTRY 2 cc.warlock.rcp 2 0 2013-03-03 11:04:50.502
!MESSAGE Missing required bundle org.eclipse.equinox.p2.updatechecker_0.0.0.
!SUBENTRY 2 cc.warlock.rcp 2 0 2013-03-03 11:04:50.502
!MESSAGE Missing required bundle org.eclipse.equinox.p2.updatesite_0.0.0.
!SUBENTRY 2 cc.warlock.rcp 2 0 2013-03-03 11:04:50.502
!MESSAGE Missing required bundle org.eclipse.equinox.ds_0.0.0.
!SUBENTRY 2 cc.warlock.rcp 2 0 2013-03-03 11:04:50.502
!MESSAGE Missing required bundle org.eclipse.equinox.event_0.0.0.

!ENTRY org.eclipse.osgi 4 0 2013-03-03 11:04:50.504
!MESSAGE Application error
!STACK 1
java.lang.RuntimeException: No application id has been found.
    at org.eclipse.equinox.internal.app.EclipseAppContainer.startDefaultApp(EclipseAppContainer.java:242)
    at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:29)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:344)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:622)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:577)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1410)

**Comment by sproctor** [comment]
Try downloading from http://build.warlock.cc/2.0.0.2355_sproctor/ We changed changed eclipse versions again, but the updater only does the Warlock stuff, not the platform stuff. This version is a little buggy. It's going to take me a bit to get the changes with eclipse 4 ironed out.

**Comment by nebula656** [comment]
Thanks.  Any tips on copying my old settings to this version?

**Comment by sproctor** [comment]
copy the configuration/.settings directory (or move the cc.warlock.prefs file from the old .settings directory to the new one)

**Comment by nebula656** [comment]
thanks again!
