### ISSUE TITLE
UP command history no longer works

### ISSUE THREAD

**Issue by ghost** [WarlockFE/warlock2#40]
Hitting UP on keyboard so that you can scroll through past commands which you have entered no longer seems to work on macosx x86_64 versions (only version type I tested though).

Going back through your build index, it seems that http://build.warlock.cc/2.0.0.2414_sproctor/ was the last version where it worked.

**Comment by sproctor** [comment]
Builds are still broken. There's a bunch of fixes waiting in git. This is working for me currently. I'll close it once I get a build out to verify.

**Comment by sproctor** [comment]
I'm closing old issues from Warlock 2. Warlock 3 isn't ready for use yet, but it might get there.
